### ISSUE TITLE
Run ElM2D on GPU

### ISSUE THREAD

**Issue by ancarnevali** [lrcfmd/ElM2D#14]
Hi!
This may be a trivial question, but I was wondering: how can I run the `fit_transform` method on my GPU? The goal is to speed up the calculation.
I'm not an expert in the use of `numba`, so feel free to add any detail that you deem relevant!

**Comment by SurgeArrester** [comment]
Hi Antonio!

I haven't investigated using cuda accelerated numba functions too much. My assumption is that whilst it is a computationally intensive distance metric, the amount of time that would be added from the interprocess communications would actually make the whole process a lot slower. This may not be a correct assumption though...

If you were to do a simple investigation into this then it would all be within the ElMD class, not in ElM2D, using the separate numba headers. If you were to design a proper data loader for GPUs then that may give a speedup, but would also be a lot more work to develop and test I think.

Would happily accept a pull request if you do get it working and it does give a speedup!

**Comment by ancarnevali** [comment]
little update: usin @sgbaird 's fork (https://github.com/sparks-baird/chem_wasserstein) I think the fitting process successfully runs on `cuda` by passing the proper `target` value to the [fit function](https://github.com/sparks-baird/chem_wasserstein/blob/8af5cfdda1ade48ece336cd83e4f241280cab162/chem_wasserstein/ElM2D_.py#L337). 

I am gettting a significant speedup: for circa 150 formulas CPU runs in 7.6 s, while `cuda` in 3.4.

 Hope this helps!

**Comment by sgbaird** [comment]
A couple drive-by comments here. Getting this to work on a GPU was a pretty big endeavor and there's still some limitations. For example this only works on scalar features as opposed to vector-based features because I based it on Scipy's version of Wasserstein distance. There will also be some overhead from the compile time, but not too much - so the gains are probably manifest more for larger sets of distances. There are a few parts of the GPU implementation that are specific to Wasserstein distance, like presorting and `np.cumsum`-ing the vectors beforehand. It's compatible with Euclidean distance and would be easy to modify for just about any other distance (or function that runs for 10k's of iterations are somewhat expensive calculations). Most of this was for the [mat_discover](https://GitHub.com/sparks-baird/mat_discover) to run fast. Took me well over 100 hours to get the GPU implementation working, so I have to admit it was a little disappointing to see a 2x speedup when the CPU version of what I described gave me ~100x speedup in ~15 minutes of code modification 😅. Good learning experience.
